CREATE TABLE CUSTOMER_DETAILS
( CUSTOMER_ID INTEGER NOT NULL,
  FNAME VARCHAR(25) NOT NULL,
  MNAME VARCHAR(15),
  LNAME VARCHAR(25) NOT NULL,
  PHONE_NUMBER VARCHAR(10) NOT NULL,
  EMAIL_ID VARCHAR(30) NOT NULL,
  CONSTRAINT CUSTOMERPK
  PRIMARY KEY (CUSTOMER_ID)
);
