CREATE TABLE CUSTOMER_DETAILS
( CUSTOMER_ID INTEGER NOT NULL,
  FNAME VARCHAR(25) NOT NULL,
  MNAME VARCHAR(15),
  LNAME VARCHAR(25) NOT NULL,
  PHONE_NUMBER VARCHAR(10) NOT NULL,
  EMAIL_ID VARCHAR(30) NOT NULL,
  CONSTRAINT CUSTOMERPK
  PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE CAR_CATEGORY
( CATEGORY_NAME VARCHAR(25) NOT NULL,
  NO_OF_PERSON INTEGER NOT NULL,
  COST_PER_DAY INTEGER NOT NULL,
  REGISTRATION_NUMBER CHAR(7) NOT NULL,
  CONSTRAINT CARCATEGORYPK
  PRIMARY KEY (CATEGORY_NAME,REGISTRATION_NUMBER),
  CONSTRAINT CARCATEGORYFK1
  FOREIGN KEY (REGISTRATION_NUMBER) REFERENCES CAR_DETAILS(REGISTRATION_NUMBER) ON DELETE CASCADE
);

CREATE TABLE LOCATION_DETAILS
( LOCATION_ID INTEGER NOT NULL,
  LOCATION_NAME VARCHAR(50) NOT NULL,
  STREET VARCHAR(30) NOT NULL,
  CITY VARCHAR(20) NOT NULL,
  STATE_NAME VARCHAR(20) NOT NULL,
  PINCODE DECIMAL(6) NOT NULL,
  CONSTRAINT LOCATIONPK
  PRIMARY KEY (LOCATION_ID)
);

CREATE TABLE CAR_DETAILS
( REGISTRATION_NUMBER CHAR(7) NOT NULL,
  MODEL_NAME VARCHAR(25) NOT NULL,
  MAKE VARCHAR(25) NOT NULL,
  AVAILABILITY_FLAG CHAR(1) NOT NULL,
  CONSTRAINT CARPK
  PRIMARY KEY (REGISTRATION_NUMBER)
);

CREATE TABLE BOOKING_DETAILS
( BOOKING_ID INTEGER NOT NULL,
  PICKUP_DT DATE NOT NULL,
  RET_DT DATE NOT NULL,
  AMOUNT INTEGER NOT NULL,
  BOOKING_STATUS CHAR(1) NOT NULL,
  PICKUP_LID  INTEGER NOT NULL,
  DROP_LID INTEGER NOT NULL,
  CONSTRAINT BOOKINGPK
  PRIMARY KEY (BOOKING_ID),
  CONSTRAINT BOOKINGFK1
  FOREIGN KEY (PICKUP_LID) REFERENCES LOCATION_DETAILS(LOCATION_ID),
  CONSTRAINT BOOKINGFK2
  FOREIGN KEY (DROP_LID) REFERENCES LOCATION_DETAILS(LOCATION_ID)
);

CREATE TABLE RENTS(
  CUSTOMER_ID INTEGER NOT NULL,
  REGISTRATION_NUMBER CHAR(7) NOT NULL,
  BOOKING_ID INTEGER NOT NULL,
  PRIMARY KEY(CUSTOMER_ID,REGISTRATION_NUMBER,BOOKING_ID),
  CONSTRAINT RENTSFK1
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_DETAILS(CUSTOMER_ID),
  CONSTRAINT RENTSFK2
  FOREIGN KEY (REGISTRATION_NUMBER) REFERENCES CAR_DETAILS(REGISTRATION_NUMBER),
  CONSTRAINT RENTSFK3
  FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING_DETAILS(BOOKING_ID)  
);






/*
DROP TABLE BILLING_DETAILS;
DROP TABLE BOOKING_DETAILS;
DROP TABLE RENTAL_CAR_INSURANCE;
DROP TABLE DISCOUNT_DETAILS;
DROP TABLE CAR;
DROP TABLE LOCATION_DETAILS;
DROP TABLE CAR_CATEGORY;
DROP TABLE CUSTOMER_DETAILS;

DROP VIEW TABLE1;
DROP VIEW TABLE2;
*/
CREATE VIEW VIEW1 AS SELECT PICKUP_LID, LOCATION_NAME,BOOKING_ID FROM BOOKING_DETAILS,LOCATION_DETALS WHERE LOCATION_ID=PICKUP_LID; 
  
