SELECT PICKUP_LID,LOCATION_NAME,BOOKING_ID FROM BOOKING_DETAILS,LOCATION_DETAILS WHERE LOCATION_ID=PICKUP_LID
SELECT R.CUSTOMER_ID,FNAME,R.REGISTRATION_NUMBER FROM RENTS AS R,CUSTOMER_DETAILS AS C WHERE C.CUSTOMER_ID=R.CUSTOMER_ID;

SELECT SUM(AMOUNT) AS 'Total amount', PICKUP_LID as 'Pick up location' FROM BOOKING_DETAILS GROUP BY PICKUP_LID;
SELECT sum(AMOUNT) as Total_amount_month,month(PICKUP_DT) as month FROM BOOKING_DETAILS GROUP BY month(PICKUP_DT);
SELECT AVG(COST_PER_DAY) AS AVG_COST ,CATEGORY_NAME FROM CAR_CATEGORY GROUP BY CATEGORY_NAME;
 
SELECT CUSTOMER_ID FROM RENTS AS R,BOOKING_DETAILS AS B WHERE R.BOOKING_ID=B.BOOKING_ID AND MONTH(PICKUP_DT)=1 UNION (SELECT CUSTOMER_ID FROM RENTS AS R,BOOKING_DETAILS AS B WHERE R.BOOKING_ID=B.BOOKING_ID AND MONTH(PICKUP_DT)=4);

SELECT CUSTOMER_ID FROM RENTS AS R,BOOKING_DETAILS AS B WHERE R.BOOKING_ID=B.BOOKING_ID AND MONTH(PICKUP_DT)=1 MINUS (SELECT CUSTOMER_ID FROM RENTS AS R,BOOKING_DETAILS AS B WHERE R.BOOKING_ID=B.BOOKING_ID AND MONTH(PICKUP_DT)=4);

SELECT 
    CUSTOMER_ID, FNAME 
FROM 
    CUSTOMER_DETAILS C 
WHERE 
    NOT EXISTS ( SELECT * 
        FROM 
            RENTS 
            WHERE 
                CUSTOMER_ID=C.CUSTOMER_ID);

SELECT 
    BOOKING_ID,AMOUNT
FROM
    BOOKING_DETAILS
WHERE
    AMOUNT > (SELECT 
            AVG(AMOUNT)
        FROM
            BOOKING_DETAILS);

SELECT 
    CUSTOMER_ID
FROM
    CUSTOMER_DETAILS C
WHERE
    NOT EXISTS( SELECT 
            *
        FROM
            RENTS 
        WHERE
            CUSTOMER_ID = C.CUSTOMER_ID)



select *from CAR_DETAILS WHERE REGISTRATION_NUMBER IN (SELECT REGISTRATION_NUMBER FROM CAR_DETAILS WHERE AVAILABILITY_FLAG='A');

select *from CAR_CATEGORY WHERE REGISTRATION_NUMBER IN (SELECT REGISTRATION_NUMBER FROM CAR_CATEGORY WHERE NO_OF_PERSON>3);
